# Setup
title:               IFT6758 Blog
tagline:             'An analysis of NHL data'
description:         'This blog was designed to present our discussions and findings regarding our work on NHL data. This project consists of analyzing and playing around with NHL data to answer the various questions of the projects and introduce a number of discussions.'
url:                 ''
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Maneesha, Chaitanya, Etienne and Mahdi
  url:              
  email:             

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
